### ISSUE TITLE
Fix text overlay on mobile

### ISSUE THREAD

**Issue by astar26** [Lev-Echad/levechad-backend#108]
Still not working (on dardik's Galaxy S9)

![image](https://user-images.githubusercontent.com/5032106/77862205-96a3e780-7222-11ea-9988-e6e292c5acce.png)

**Comment by stavlocker** [comment]
![Screenshot_20200330-125940](https://user-images.githubusercontent.com/30472563/77900287-84f42b80-7286-11ea-9337-87a727e7e1e7.jpg)
On my OnePlus 6 the height seems to not be automatic, other than that things look fine

**Comment by astar26** [comment]
Also okay on OnePlus7, need to check with resolution of Galaxy S9 (1440 x 2960) and a random Xiaomi (didn't get model, my guess is 720p).

**Comment by stavlocker** [comment]
Irrelevant as of the new frontend
