### ISSUE TITLE
Add & fix phone number validation to VolunteerForm

### ISSUE THREAD

**Issue by stavlocker** [Lev-Echad/levechad-backend#117]
* Currently only the BaseHelpForm has phone number validation.
This validation should occur in VolunteerForm as well.
* Also, this sort of validation does not seem like it would capture all phone numbers. We need to rethink this - maybe it should be a freeform combination of numbers, plus and minus signs limited to a certain amount of characters (see #49)

Don't do before #45 is merged as the phone number validation should be similar to how the ID number validation was done in said issue.

**Comment by ykrinsky** [comment]
Hi, I would be happy to solve this issue 😄. 
Could you make me a collaborator? So I could assign myself to this issue.
