### ISSUE TITLE
Build framework for volunteer log in.

### ISSUE THREAD

**Issue by astar26** [Lev-Echad/levechad-backend#183]
Needs to be done carefully, currently django users are able to see all hamal related items.
To be done while consulting @astar26

**Comment by stavlocker** [comment]
Excellent!
Django has built-in [permissions and groups](https://docs.djangoproject.com/en/3.0/topics/auth/default/#permissions-and-authorization) so make sure to check that out.

**Comment by stavlocker** [comment]
Duplicated by #212
