### ISSUE TITLE
Add validation of minimum age at registration.

### ISSUE THREAD

**Issue by ykrinsky** [Lev-Echad/levechad-backend#282]
**Related component**: `api` app, `client` app.

## Description
Currently, there isn't a limitation on the minimum age of a volunteer. But there should be one, as the minimum age of a volunteer is 16.

Add a custom validation function that only fires a validation error if the age of a new volunteer is under 16 years old.

----
### Prerequisites
_[Make sure you've done the following before posting your issue:]_
* [x] I have filled in the correct labels (fill at least one of bug/enhancement)
* [x] I have searched for duplicate issues and found none
* [x] My issue is phrased as a task - it's clear what needs to be done here.

**Comment by ykrinsky** [comment]
I can do this issue myself, but I don't know if the validation should also be added at Volunteer in clients/models.py .
This will enforce the minimum age also on the current app (`client`). and I didn't fully understand if we can or can't add constraints/validation to existing fields in client app. Or, if we just add validation on the new app `api`.

I would also add validation at RegistrationSerializer to enforce minimum age in the new app `api`. 

@stavlocker do you think the validation should also be added to Volunteer model ?

**Comment by stavlocker** [comment]
@ykrinsky great - this should be validated at the Volunteer model, limited both on the old system (`client`) and the new one (`api`).

**Comment by ykrinsky** [comment]
@stavlocker inserting the validation at the Volunteer model would limit the minimum age on both systems.
But, for some reason, other validations such as id number and phone number validation are done on Forms level (specifically on VolunteerForm), and I assume there is a reason for that.

Possible ideas to why have validations done on VolunteerForm and not on Volunteer model:
- Maybe we want admins to enters whichever Volunteers they want using the admin interface (bypassing any validations).
- Maybe adding validation to Models can effect existing entries in the DB?

Currently, I don't know the reason for that and I don't want to accidentally change the design of the app.  @stavlocker or @astar26 what do you think?

If we don't want to do the validation on Volunteer model, we can add it to both RegistrationSerializer and VolunteerFrom (so it will included in both old and new systems).

**Comment by stavlocker** [comment]
@ykrinsky In Django, model validations aren't executed by default and are only done on save. This is for backwards-compatability reasons.

We don't have this validation because we currently have some entries in the DB that do not match our validations (For example validations we only added after the entries were already in the system).

Add this to wherever you see fit for it to work both on the old system and the new system.
