### ISSUE TITLE
Add code-style workflow

### ISSUE THREAD

**Issue by GuyOmer** [Lev-Echad/levechad-backend#96]
We want each opened PR to have autopep8 executed on it.

**Comment by itay-sho** [comment]
our first steps toward CI :-)

**Comment by stavlocker** [comment]
We should take a look at Github Actions as they seem to be free for open source & integrated here (see Actions tab above)

**Comment by GuyOmer** [comment]
Exactly what we will be doing 🥇 
You can follow up on https://github.com/itay-sho/LevEchad/tree/Workflow-code-style (checkout .github/)
